apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::998753390872:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::998753390872:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8EQYWHIL6340
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-19T17:18:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1137"
  uid: b96680e6-aeac-44a6-b5ba-c07943b7ec10
